// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package raydium_cp_swap

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Deposit lp token to the pool
//
// # Arguments
//
// * `ctx`- The context of accounts
// * `lp_token_amount` - Pool token amount to transfer. token_a and token_b amount are set by the current exchange rate and size of the pool
// * `maximum_token_0_amount` -  Maximum token 0 amount to deposit, prevents excessive slippage
// * `maximum_token_1_amount` - Maximum token 1 amount to deposit, prevents excessive slippage
//
type DepositInstruction struct {
	LpTokenAmount       *uint64
	MaximumToken0Amount *uint64
	MaximumToken1Amount *uint64

	// [0] = [SIGNER] owner
	// ··········· Pays to mint the position
	//
	// [1] = [] authority
	//
	// [2] = [WRITE] pool_state
	//
	// [3] = [WRITE] owner_lp_token
	// ··········· Owner lp token account
	//
	// [4] = [WRITE] token_0_account
	// ··········· The payer's token account for token_0
	//
	// [5] = [WRITE] token_1_account
	// ··········· The payer's token account for token_1
	//
	// [6] = [WRITE] token_0_vault
	// ··········· The address that holds pool tokens for token_0
	//
	// [7] = [WRITE] token_1_vault
	// ··········· The address that holds pool tokens for token_1
	//
	// [8] = [] token_program
	// ··········· token Program
	//
	// [9] = [] token_program_2022
	// ··········· Token program 2022
	//
	// [10] = [] vault_0_mint
	// ··········· The mint of token_0 vault
	//
	// [11] = [] vault_1_mint
	// ··········· The mint of token_1 vault
	//
	// [12] = [WRITE] lp_mint
	// ··········· Lp token mint
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewDepositInstructionBuilder creates a new `DepositInstruction` instruction builder.
func NewDepositInstructionBuilder() *DepositInstruction {
	nd := &DepositInstruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 13),
	}
	nd.AccountMetaSlice[8] = ag_solanago.Meta(Addresses["TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"])
	nd.AccountMetaSlice[9] = ag_solanago.Meta(Addresses["TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"])
	return nd
}

// SetLpTokenAmount sets the "lp_token_amount" parameter.
func (inst *DepositInstruction) SetLpTokenAmount(lp_token_amount uint64) *DepositInstruction {
	inst.LpTokenAmount = &lp_token_amount
	return inst
}

// SetMaximumToken0Amount sets the "maximum_token_0_amount" parameter.
func (inst *DepositInstruction) SetMaximumToken0Amount(maximum_token_0_amount uint64) *DepositInstruction {
	inst.MaximumToken0Amount = &maximum_token_0_amount
	return inst
}

// SetMaximumToken1Amount sets the "maximum_token_1_amount" parameter.
func (inst *DepositInstruction) SetMaximumToken1Amount(maximum_token_1_amount uint64) *DepositInstruction {
	inst.MaximumToken1Amount = &maximum_token_1_amount
	return inst
}

// SetOwnerAccount sets the "owner" account.
// Pays to mint the position
func (inst *DepositInstruction) SetOwnerAccount(owner ag_solanago.PublicKey) *DepositInstruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(owner).SIGNER()
	return inst
}

// GetOwnerAccount gets the "owner" account.
// Pays to mint the position
func (inst *DepositInstruction) GetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *DepositInstruction) SetAuthorityAccount(authority ag_solanago.PublicKey) *DepositInstruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority)
	return inst
}

func (inst *DepositInstruction) findFindAuthorityAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: vault_and_lp_mint_auth_seed
	seeds = append(seeds, []byte{byte(0x76), byte(0x61), byte(0x75), byte(0x6c), byte(0x74), byte(0x5f), byte(0x61), byte(0x6e), byte(0x64), byte(0x5f), byte(0x6c), byte(0x70), byte(0x5f), byte(0x6d), byte(0x69), byte(0x6e), byte(0x74), byte(0x5f), byte(0x61), byte(0x75), byte(0x74), byte(0x68), byte(0x5f), byte(0x73), byte(0x65), byte(0x65), byte(0x64)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindAuthorityAddressWithBumpSeed calculates Authority account address with given seeds and a known bump seed.
func (inst *DepositInstruction) FindAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindAuthorityAddress(bumpSeed)
	return
}

func (inst *DepositInstruction) MustFindAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindAuthorityAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindAuthorityAddress finds Authority account address with given seeds.
func (inst *DepositInstruction) FindAuthorityAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindAuthorityAddress(0)
	return
}

func (inst *DepositInstruction) MustFindAuthorityAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindAuthorityAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetAuthorityAccount gets the "authority" account.
func (inst *DepositInstruction) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetPoolStateAccount sets the "pool_state" account.
func (inst *DepositInstruction) SetPoolStateAccount(poolState ag_solanago.PublicKey) *DepositInstruction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(poolState).WRITE()
	return inst
}

// GetPoolStateAccount gets the "pool_state" account.
func (inst *DepositInstruction) GetPoolStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetOwnerLpTokenAccount sets the "owner_lp_token" account.
// Owner lp token account
func (inst *DepositInstruction) SetOwnerLpTokenAccount(ownerLpToken ag_solanago.PublicKey) *DepositInstruction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(ownerLpToken).WRITE()
	return inst
}

// GetOwnerLpTokenAccount gets the "owner_lp_token" account.
// Owner lp token account
func (inst *DepositInstruction) GetOwnerLpTokenAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetToken0AccountAccount sets the "token_0_account" account.
// The payer's token account for token_0
func (inst *DepositInstruction) SetToken0AccountAccount(token0Account ag_solanago.PublicKey) *DepositInstruction {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(token0Account).WRITE()
	return inst
}

// GetToken0AccountAccount gets the "token_0_account" account.
// The payer's token account for token_0
func (inst *DepositInstruction) GetToken0AccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetToken1AccountAccount sets the "token_1_account" account.
// The payer's token account for token_1
func (inst *DepositInstruction) SetToken1AccountAccount(token1Account ag_solanago.PublicKey) *DepositInstruction {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(token1Account).WRITE()
	return inst
}

// GetToken1AccountAccount gets the "token_1_account" account.
// The payer's token account for token_1
func (inst *DepositInstruction) GetToken1AccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetToken0VaultAccount sets the "token_0_vault" account.
// The address that holds pool tokens for token_0
func (inst *DepositInstruction) SetToken0VaultAccount(token0Vault ag_solanago.PublicKey) *DepositInstruction {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(token0Vault).WRITE()
	return inst
}

// GetToken0VaultAccount gets the "token_0_vault" account.
// The address that holds pool tokens for token_0
func (inst *DepositInstruction) GetToken0VaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetToken1VaultAccount sets the "token_1_vault" account.
// The address that holds pool tokens for token_1
func (inst *DepositInstruction) SetToken1VaultAccount(token1Vault ag_solanago.PublicKey) *DepositInstruction {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(token1Vault).WRITE()
	return inst
}

// GetToken1VaultAccount gets the "token_1_vault" account.
// The address that holds pool tokens for token_1
func (inst *DepositInstruction) GetToken1VaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetTokenProgramAccount sets the "token_program" account.
// token Program
func (inst *DepositInstruction) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *DepositInstruction {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "token_program" account.
// token Program
func (inst *DepositInstruction) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetTokenProgram2022Account sets the "token_program_2022" account.
// Token program 2022
func (inst *DepositInstruction) SetTokenProgram2022Account(tokenProgram2022 ag_solanago.PublicKey) *DepositInstruction {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(tokenProgram2022)
	return inst
}

// GetTokenProgram2022Account gets the "token_program_2022" account.
// Token program 2022
func (inst *DepositInstruction) GetTokenProgram2022Account() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetVault0MintAccount sets the "vault_0_mint" account.
// The mint of token_0 vault
func (inst *DepositInstruction) SetVault0MintAccount(vault0Mint ag_solanago.PublicKey) *DepositInstruction {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(vault0Mint)
	return inst
}

// GetVault0MintAccount gets the "vault_0_mint" account.
// The mint of token_0 vault
func (inst *DepositInstruction) GetVault0MintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetVault1MintAccount sets the "vault_1_mint" account.
// The mint of token_1 vault
func (inst *DepositInstruction) SetVault1MintAccount(vault1Mint ag_solanago.PublicKey) *DepositInstruction {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(vault1Mint)
	return inst
}

// GetVault1MintAccount gets the "vault_1_mint" account.
// The mint of token_1 vault
func (inst *DepositInstruction) GetVault1MintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetLpMintAccount sets the "lp_mint" account.
// Lp token mint
func (inst *DepositInstruction) SetLpMintAccount(lpMint ag_solanago.PublicKey) *DepositInstruction {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(lpMint).WRITE()
	return inst
}

// GetLpMintAccount gets the "lp_mint" account.
// Lp token mint
func (inst *DepositInstruction) GetLpMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

func (inst DepositInstruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Deposit,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst DepositInstruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *DepositInstruction) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.LpTokenAmount == nil {
			return errors.New("LpTokenAmount parameter is not set")
		}
		if inst.MaximumToken0Amount == nil {
			return errors.New("MaximumToken0Amount parameter is not set")
		}
		if inst.MaximumToken1Amount == nil {
			return errors.New("MaximumToken1Amount parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Owner is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.PoolState is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.OwnerLpToken is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Token0Account is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Token1Account is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Token0Vault is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.Token1Vault is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.TokenProgram2022 is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.Vault0Mint is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.Vault1Mint is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.LpMint is not set")
		}
	}
	return nil
}

func (inst *DepositInstruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Deposit")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=3]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("         LpTokenAmount", *inst.LpTokenAmount))
						paramsBranch.Child(ag_format.Param("   MaximumToken0Amount", *inst.MaximumToken0Amount))
						paramsBranch.Child(ag_format.Param("   MaximumToken1Amount", *inst.MaximumToken1Amount))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=13]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("             owner", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("         authority", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("        pool_state", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("    owner_lp_token", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("          token_0_", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("          token_1_", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("     token_0_vault", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("     token_1_vault", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("     token_program", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("token_program_2022", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("      vault_0_mint", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("      vault_1_mint", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("           lp_mint", inst.AccountMetaSlice.Get(12)))
					})
				})
		})
}

func (obj DepositInstruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `LpTokenAmount` param:
	err = encoder.Encode(obj.LpTokenAmount)
	if err != nil {
		return err
	}
	// Serialize `MaximumToken0Amount` param:
	err = encoder.Encode(obj.MaximumToken0Amount)
	if err != nil {
		return err
	}
	// Serialize `MaximumToken1Amount` param:
	err = encoder.Encode(obj.MaximumToken1Amount)
	if err != nil {
		return err
	}
	return nil
}
func (obj *DepositInstruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `LpTokenAmount`:
	err = decoder.Decode(&obj.LpTokenAmount)
	if err != nil {
		return err
	}
	// Deserialize `MaximumToken0Amount`:
	err = decoder.Decode(&obj.MaximumToken0Amount)
	if err != nil {
		return err
	}
	// Deserialize `MaximumToken1Amount`:
	err = decoder.Decode(&obj.MaximumToken1Amount)
	if err != nil {
		return err
	}
	return nil
}

// NewDepositInstruction declares a new Deposit instruction with the provided parameters and accounts.
func NewDepositInstruction(
	// Parameters:
	lp_token_amount uint64,
	maximum_token_0_amount uint64,
	maximum_token_1_amount uint64,
	// Accounts:
	owner ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	poolState ag_solanago.PublicKey,
	ownerLpToken ag_solanago.PublicKey,
	token0Account ag_solanago.PublicKey,
	token1Account ag_solanago.PublicKey,
	token0Vault ag_solanago.PublicKey,
	token1Vault ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	tokenProgram2022 ag_solanago.PublicKey,
	vault0Mint ag_solanago.PublicKey,
	vault1Mint ag_solanago.PublicKey,
	lpMint ag_solanago.PublicKey) *DepositInstruction {
	return NewDepositInstructionBuilder().
		SetLpTokenAmount(lp_token_amount).
		SetMaximumToken0Amount(maximum_token_0_amount).
		SetMaximumToken1Amount(maximum_token_1_amount).
		SetOwnerAccount(owner).
		SetAuthorityAccount(authority).
		SetPoolStateAccount(poolState).
		SetOwnerLpTokenAccount(ownerLpToken).
		SetToken0AccountAccount(token0Account).
		SetToken1AccountAccount(token1Account).
		SetToken0VaultAccount(token0Vault).
		SetToken1VaultAccount(token1Vault).
		SetTokenProgramAccount(tokenProgram).
		SetTokenProgram2022Account(tokenProgram2022).
		SetVault0MintAccount(vault0Mint).
		SetVault1MintAccount(vault1Mint).
		SetLpMintAccount(lpMint)
}
