// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package raydium_cp_swap

import (
	"encoding/json"
	"errors"
	"fmt"
	ag_jsonrpc "github.com/gagliardetto/solana-go/rpc/jsonrpc"
)

var (
	_ *json.Encoder        = nil
	_ *ag_jsonrpc.RPCError = nil
	_ fmt.Formatter        = nil
	_                      = errors.ErrUnsupported
)
var (
	ErrNotApproved = &customErrorDef{
		code: 6000,
		msg:  "Not approved",
		name: "NotApproved",
	}
	ErrInvalidOwner = &customErrorDef{
		code: 6001,
		msg:  "Input account owner is not the program address",
		name: "InvalidOwner",
	}
	ErrEmptySupply = &customErrorDef{
		code: 6002,
		msg:  "Input token account empty",
		name: "EmptySupply",
	}
	ErrInvalidInput = &customErrorDef{
		code: 6003,
		msg:  "InvalidInput",
		name: "InvalidInput",
	}
	ErrIncorrectLpMint = &customErrorDef{
		code: 6004,
		msg:  "Address of the provided lp token mint is incorrect",
		name: "IncorrectLpMint",
	}
	ErrExceededSlippage = &customErrorDef{
		code: 6005,
		msg:  "Exceeds desired slippage limit",
		name: "ExceededSlippage",
	}
	ErrZeroTradingTokens = &customErrorDef{
		code: 6006,
		msg:  "Given pool token amount results in zero trading tokens",
		name: "ZeroTradingTokens",
	}
	ErrNotSupportMint = &customErrorDef{
		code: 6007,
		msg:  "Not support token_2022 mint extension",
		name: "NotSupportMint",
	}
	ErrInvalidVault = &customErrorDef{
		code: 6008,
		msg:  "invaild vault",
		name: "InvalidVault",
	}
	ErrInitLpAmountTooLess = &customErrorDef{
		code: 6009,
		msg:  "Init lp amount is too less(Because 100 amount lp will be locked)",
		name: "InitLpAmountTooLess",
	}
	ErrTransferFeeCalculateNotMatch = &customErrorDef{
		code: 6010,
		msg:  "TransferFee calculate not match",
		name: "TransferFeeCalculateNotMatch",
	}
	Errors = map[int]CustomError{
		6000: ErrNotApproved,
		6001: ErrInvalidOwner,
		6002: ErrEmptySupply,
		6003: ErrInvalidInput,
		6004: ErrIncorrectLpMint,
		6005: ErrExceededSlippage,
		6006: ErrZeroTradingTokens,
		6007: ErrNotSupportMint,
		6008: ErrInvalidVault,
		6009: ErrInitLpAmountTooLess,
		6010: ErrTransferFeeCalculateNotMatch,
	}
)

type CustomError interface {
	Code() int
	Name() string
	Error() string
}

type customErrorDef struct {
	code int
	name string
	msg  string
}

func (e *customErrorDef) Code() int {
	return e.code
}

func (e *customErrorDef) Name() string {
	return e.name
}

func (e *customErrorDef) Error() string {
	return fmt.Sprintf("%s(%d): %s", e.name, e.code, e.msg)
}

func DecodeCustomError(rpcErr error) (err error, ok bool) {
	if errCode, o := decodeErrorCode(rpcErr); o {
		if customErr, o := Errors[errCode]; o {
			err = customErr
			ok = true
			return
		}
	}
	return
}

func decodeErrorCode(rpcErr error) (errorCode int, ok bool) {
	var jErr *ag_jsonrpc.RPCError
	if errors.As(rpcErr, &jErr) && jErr.Data != nil {
		if root, o := jErr.Data.(map[string]interface{}); o {
			if rootErr, o := root["err"].(map[string]interface{}); o {
				if rootErrInstructionError, o := rootErr["InstructionError"]; o {
					if rootErrInstructionErrorItems, o := rootErrInstructionError.([]interface{}); o {
						if len(rootErrInstructionErrorItems) == 2 {
							if v, o := rootErrInstructionErrorItems[1].(map[string]interface{}); o {
								if v2, o := v["Custom"].(json.Number); o {
									if code, err := v2.Int64(); err == nil {
										ok = true
										errorCode = int(code)
									}
								} else if v2, o := v["Custom"].(float64); o {
									ok = true
									errorCode = int(v2)
								}
							}
						}
					}
				}
			}
		}
	}
	return
}
