// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package raydium_cp_swap

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Swap the tokens in the pool base output amount
//
// # Arguments
//
// * `ctx`- The context of accounts
// * `max_amount_in` -  input amount prevents excessive slippage
// * `amount_out` -  amount of output token
//
type SwapBaseOutputInstruction struct {
	MaxAmountIn *uint64
	AmountOut   *uint64

	// [0] = [SIGNER] payer
	// ··········· The user performing the swap
	//
	// [1] = [] authority
	//
	// [2] = [] amm_config
	// ··········· The factory state to read protocol fees
	//
	// [3] = [WRITE] pool_state
	// ··········· The program account of the pool in which the swap will be performed
	//
	// [4] = [WRITE] input_token_account
	// ··········· The user token account for input token
	//
	// [5] = [WRITE] output_token_account
	// ··········· The user token account for output token
	//
	// [6] = [WRITE] input_vault
	// ··········· The vault token account for input token
	//
	// [7] = [WRITE] output_vault
	// ··········· The vault token account for output token
	//
	// [8] = [] input_token_program
	// ··········· SPL program for input token transfers
	//
	// [9] = [] output_token_program
	// ··········· SPL program for output token transfers
	//
	// [10] = [] input_token_mint
	// ··········· The mint of input token
	//
	// [11] = [] output_token_mint
	// ··········· The mint of output token
	//
	// [12] = [WRITE] observation_state
	// ··········· The program account for the most recent oracle observation
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSwapBaseOutputInstructionBuilder creates a new `SwapBaseOutputInstruction` instruction builder.
func NewSwapBaseOutputInstructionBuilder() *SwapBaseOutputInstruction {
	nd := &SwapBaseOutputInstruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 13),
	}
	return nd
}

// SetMaxAmountIn sets the "max_amount_in" parameter.
func (inst *SwapBaseOutputInstruction) SetMaxAmountIn(max_amount_in uint64) *SwapBaseOutputInstruction {
	inst.MaxAmountIn = &max_amount_in
	return inst
}

// SetAmountOut sets the "amount_out" parameter.
func (inst *SwapBaseOutputInstruction) SetAmountOut(amount_out uint64) *SwapBaseOutputInstruction {
	inst.AmountOut = &amount_out
	return inst
}

// SetPayerAccount sets the "payer" account.
// The user performing the swap
func (inst *SwapBaseOutputInstruction) SetPayerAccount(payer ag_solanago.PublicKey) *SwapBaseOutputInstruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(payer).SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
// The user performing the swap
func (inst *SwapBaseOutputInstruction) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *SwapBaseOutputInstruction) SetAuthorityAccount(authority ag_solanago.PublicKey) *SwapBaseOutputInstruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority)
	return inst
}

func (inst *SwapBaseOutputInstruction) findFindAuthorityAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: vault_and_lp_mint_auth_seed
	seeds = append(seeds, []byte{byte(0x76), byte(0x61), byte(0x75), byte(0x6c), byte(0x74), byte(0x5f), byte(0x61), byte(0x6e), byte(0x64), byte(0x5f), byte(0x6c), byte(0x70), byte(0x5f), byte(0x6d), byte(0x69), byte(0x6e), byte(0x74), byte(0x5f), byte(0x61), byte(0x75), byte(0x74), byte(0x68), byte(0x5f), byte(0x73), byte(0x65), byte(0x65), byte(0x64)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(knownBumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindAuthorityAddressWithBumpSeed calculates Authority account address with given seeds and a known bump seed.
func (inst *SwapBaseOutputInstruction) FindAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindAuthorityAddress(bumpSeed)
	return
}

func (inst *SwapBaseOutputInstruction) MustFindAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindAuthorityAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindAuthorityAddress finds Authority account address with given seeds.
func (inst *SwapBaseOutputInstruction) FindAuthorityAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindAuthorityAddress(0)
	return
}

func (inst *SwapBaseOutputInstruction) MustFindAuthorityAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindAuthorityAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetAuthorityAccount gets the "authority" account.
func (inst *SwapBaseOutputInstruction) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetAmmConfigAccount sets the "amm_config" account.
// The factory state to read protocol fees
func (inst *SwapBaseOutputInstruction) SetAmmConfigAccount(ammConfig ag_solanago.PublicKey) *SwapBaseOutputInstruction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(ammConfig)
	return inst
}

// GetAmmConfigAccount gets the "amm_config" account.
// The factory state to read protocol fees
func (inst *SwapBaseOutputInstruction) GetAmmConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetPoolStateAccount sets the "pool_state" account.
// The program account of the pool in which the swap will be performed
func (inst *SwapBaseOutputInstruction) SetPoolStateAccount(poolState ag_solanago.PublicKey) *SwapBaseOutputInstruction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(poolState).WRITE()
	return inst
}

// GetPoolStateAccount gets the "pool_state" account.
// The program account of the pool in which the swap will be performed
func (inst *SwapBaseOutputInstruction) GetPoolStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetInputTokenAccountAccount sets the "input_token_account" account.
// The user token account for input token
func (inst *SwapBaseOutputInstruction) SetInputTokenAccountAccount(inputTokenAccount ag_solanago.PublicKey) *SwapBaseOutputInstruction {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(inputTokenAccount).WRITE()
	return inst
}

// GetInputTokenAccountAccount gets the "input_token_account" account.
// The user token account for input token
func (inst *SwapBaseOutputInstruction) GetInputTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetOutputTokenAccountAccount sets the "output_token_account" account.
// The user token account for output token
func (inst *SwapBaseOutputInstruction) SetOutputTokenAccountAccount(outputTokenAccount ag_solanago.PublicKey) *SwapBaseOutputInstruction {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(outputTokenAccount).WRITE()
	return inst
}

// GetOutputTokenAccountAccount gets the "output_token_account" account.
// The user token account for output token
func (inst *SwapBaseOutputInstruction) GetOutputTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetInputVaultAccount sets the "input_vault" account.
// The vault token account for input token
func (inst *SwapBaseOutputInstruction) SetInputVaultAccount(inputVault ag_solanago.PublicKey) *SwapBaseOutputInstruction {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(inputVault).WRITE()
	return inst
}

// GetInputVaultAccount gets the "input_vault" account.
// The vault token account for input token
func (inst *SwapBaseOutputInstruction) GetInputVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetOutputVaultAccount sets the "output_vault" account.
// The vault token account for output token
func (inst *SwapBaseOutputInstruction) SetOutputVaultAccount(outputVault ag_solanago.PublicKey) *SwapBaseOutputInstruction {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(outputVault).WRITE()
	return inst
}

// GetOutputVaultAccount gets the "output_vault" account.
// The vault token account for output token
func (inst *SwapBaseOutputInstruction) GetOutputVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetInputTokenProgramAccount sets the "input_token_program" account.
// SPL program for input token transfers
func (inst *SwapBaseOutputInstruction) SetInputTokenProgramAccount(inputTokenProgram ag_solanago.PublicKey) *SwapBaseOutputInstruction {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(inputTokenProgram)
	return inst
}

// GetInputTokenProgramAccount gets the "input_token_program" account.
// SPL program for input token transfers
func (inst *SwapBaseOutputInstruction) GetInputTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetOutputTokenProgramAccount sets the "output_token_program" account.
// SPL program for output token transfers
func (inst *SwapBaseOutputInstruction) SetOutputTokenProgramAccount(outputTokenProgram ag_solanago.PublicKey) *SwapBaseOutputInstruction {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(outputTokenProgram)
	return inst
}

// GetOutputTokenProgramAccount gets the "output_token_program" account.
// SPL program for output token transfers
func (inst *SwapBaseOutputInstruction) GetOutputTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetInputTokenMintAccount sets the "input_token_mint" account.
// The mint of input token
func (inst *SwapBaseOutputInstruction) SetInputTokenMintAccount(inputTokenMint ag_solanago.PublicKey) *SwapBaseOutputInstruction {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(inputTokenMint)
	return inst
}

// GetInputTokenMintAccount gets the "input_token_mint" account.
// The mint of input token
func (inst *SwapBaseOutputInstruction) GetInputTokenMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetOutputTokenMintAccount sets the "output_token_mint" account.
// The mint of output token
func (inst *SwapBaseOutputInstruction) SetOutputTokenMintAccount(outputTokenMint ag_solanago.PublicKey) *SwapBaseOutputInstruction {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(outputTokenMint)
	return inst
}

// GetOutputTokenMintAccount gets the "output_token_mint" account.
// The mint of output token
func (inst *SwapBaseOutputInstruction) GetOutputTokenMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetObservationStateAccount sets the "observation_state" account.
// The program account for the most recent oracle observation
func (inst *SwapBaseOutputInstruction) SetObservationStateAccount(observationState ag_solanago.PublicKey) *SwapBaseOutputInstruction {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(observationState).WRITE()
	return inst
}

// GetObservationStateAccount gets the "observation_state" account.
// The program account for the most recent oracle observation
func (inst *SwapBaseOutputInstruction) GetObservationStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

func (inst SwapBaseOutputInstruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SwapBaseOutput,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SwapBaseOutputInstruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SwapBaseOutputInstruction) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.MaxAmountIn == nil {
			return errors.New("MaxAmountIn parameter is not set")
		}
		if inst.AmountOut == nil {
			return errors.New("AmountOut parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.AmmConfig is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.PoolState is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.InputTokenAccount is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.OutputTokenAccount is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.InputVault is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.OutputVault is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.InputTokenProgram is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.OutputTokenProgram is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.InputTokenMint is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.OutputTokenMint is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.ObservationState is not set")
		}
	}
	return nil
}

func (inst *SwapBaseOutputInstruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SwapBaseOutput")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("  MaxAmountIn", *inst.MaxAmountIn))
						paramsBranch.Child(ag_format.Param("    AmountOut", *inst.AmountOut))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=13]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("               payer", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("           authority", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("          amm_config", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("          pool_state", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("        input_token_", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("       output_token_", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("         input_vault", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("        output_vault", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta(" input_token_program", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("output_token_program", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("    input_token_mint", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("   output_token_mint", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("   observation_state", inst.AccountMetaSlice.Get(12)))
					})
				})
		})
}

func (obj SwapBaseOutputInstruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `MaxAmountIn` param:
	err = encoder.Encode(obj.MaxAmountIn)
	if err != nil {
		return err
	}
	// Serialize `AmountOut` param:
	err = encoder.Encode(obj.AmountOut)
	if err != nil {
		return err
	}
	return nil
}
func (obj *SwapBaseOutputInstruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `MaxAmountIn`:
	err = decoder.Decode(&obj.MaxAmountIn)
	if err != nil {
		return err
	}
	// Deserialize `AmountOut`:
	err = decoder.Decode(&obj.AmountOut)
	if err != nil {
		return err
	}
	return nil
}

// NewSwapBaseOutputInstruction declares a new SwapBaseOutput instruction with the provided parameters and accounts.
func NewSwapBaseOutputInstruction(
	// Parameters:
	max_amount_in uint64,
	amount_out uint64,
	// Accounts:
	payer ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	ammConfig ag_solanago.PublicKey,
	poolState ag_solanago.PublicKey,
	inputTokenAccount ag_solanago.PublicKey,
	outputTokenAccount ag_solanago.PublicKey,
	inputVault ag_solanago.PublicKey,
	outputVault ag_solanago.PublicKey,
	inputTokenProgram ag_solanago.PublicKey,
	outputTokenProgram ag_solanago.PublicKey,
	inputTokenMint ag_solanago.PublicKey,
	outputTokenMint ag_solanago.PublicKey,
	observationState ag_solanago.PublicKey) *SwapBaseOutputInstruction {
	return NewSwapBaseOutputInstructionBuilder().
		SetMaxAmountIn(max_amount_in).
		SetAmountOut(amount_out).
		SetPayerAccount(payer).
		SetAuthorityAccount(authority).
		SetAmmConfigAccount(ammConfig).
		SetPoolStateAccount(poolState).
		SetInputTokenAccountAccount(inputTokenAccount).
		SetOutputTokenAccountAccount(outputTokenAccount).
		SetInputVaultAccount(inputVault).
		SetOutputVaultAccount(outputVault).
		SetInputTokenProgramAccount(inputTokenProgram).
		SetOutputTokenProgramAccount(outputTokenProgram).
		SetInputTokenMintAccount(inputTokenMint).
		SetOutputTokenMintAccount(outputTokenMint).
		SetObservationStateAccount(observationState)
}
