// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package raydium_cp_swap

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Update pool status for given value
//
// # Arguments
//
// * `ctx`- The context of accounts
// * `status` - The value of status
//
type UpdatePoolStatusInstruction struct {
	Status *uint8

	// [0] = [SIGNER] authority
	//
	// [1] = [WRITE] pool_state
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUpdatePoolStatusInstructionBuilder creates a new `UpdatePoolStatusInstruction` instruction builder.
func NewUpdatePoolStatusInstructionBuilder() *UpdatePoolStatusInstruction {
	nd := &UpdatePoolStatusInstruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	nd.AccountMetaSlice[0] = ag_solanago.Meta(Addresses["GThUX1Atko4tqhN2NaiTazWSeFWMuiUvfFnyJyUghFMJ"]).SIGNER()
	return nd
}

// SetStatus sets the "status" parameter.
func (inst *UpdatePoolStatusInstruction) SetStatus(status uint8) *UpdatePoolStatusInstruction {
	inst.Status = &status
	return inst
}

// SetAuthorityAccount sets the "authority" account.
func (inst *UpdatePoolStatusInstruction) SetAuthorityAccount(authority ag_solanago.PublicKey) *UpdatePoolStatusInstruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(authority).SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *UpdatePoolStatusInstruction) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetPoolStateAccount sets the "pool_state" account.
func (inst *UpdatePoolStatusInstruction) SetPoolStateAccount(poolState ag_solanago.PublicKey) *UpdatePoolStatusInstruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(poolState).WRITE()
	return inst
}

// GetPoolStateAccount gets the "pool_state" account.
func (inst *UpdatePoolStatusInstruction) GetPoolStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst UpdatePoolStatusInstruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_UpdatePoolStatus,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UpdatePoolStatusInstruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UpdatePoolStatusInstruction) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Status == nil {
			return errors.New("Status parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.PoolState is not set")
		}
	}
	return nil
}

func (inst *UpdatePoolStatusInstruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UpdatePoolStatus")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Status", *inst.Status))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta(" authority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("pool_state", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj UpdatePoolStatusInstruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Status` param:
	err = encoder.Encode(obj.Status)
	if err != nil {
		return err
	}
	return nil
}
func (obj *UpdatePoolStatusInstruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Status`:
	err = decoder.Decode(&obj.Status)
	if err != nil {
		return err
	}
	return nil
}

// NewUpdatePoolStatusInstruction declares a new UpdatePoolStatus instruction with the provided parameters and accounts.
func NewUpdatePoolStatusInstruction(
	// Parameters:
	status uint8,
	// Accounts:
	authority ag_solanago.PublicKey,
	poolState ag_solanago.PublicKey) *UpdatePoolStatusInstruction {
	return NewUpdatePoolStatusInstructionBuilder().
		SetStatus(status).
		SetAuthorityAccount(authority).
		SetPoolStateAccount(poolState)
}
